[workspace]
members = ["client", "server", "shared", "nserde-into-vec"]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
codegen-units = 1
incremental = false

[patch.crates-io]
